version: '3'

services:
  db:
    image: postgres:11-alpine
    container_name: pgdb
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=tidedbu
      - POSTGRES_PASSWORD=mysecretpassword 
      - POSTGRES_DB=tide
    networks:
      - backend
    ports:
      - "5432:5432/tcp"
  web:
    container_name: tide_web
    build: .
    tty: true
    command: python /code/tidebilling/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./new:/code
    networks:
      - backend
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  dbdata:
    driver: local

networks: 
  backend: